name: PR check

on:
  pull_request:
    branches: [main]

jobs:
  format_lint_test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '>=14.18.2'
          cache: 'npm'
      - run: npm ci
      - name: Prettier check
        run: npm run prettier:check
      - name: Lint check
        run: npm run lint:check
      - name: Run test
        run: npm t
      - name: Run build
        run: npm run build
