name: PR check

on:
  pull_request:
    branches: [main, develop]

jobs:
  format_lint_test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '>=14.18.2'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm t
